{% set version = "0.5.0" %}
{% set github = "https://github.com/acidgenomics/r-panther" %}

package:
  name: r-panther
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: e636e0e6ec3bbaf382609f93f2b02311db3b9138a4819e777176cabd07e7a05c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.6.18
    - r-acidcli >=0.2.8
    - r-acidgenerics >=0.6.7
    - r-acidgenomes >=0.5.1
    - r-acidplyr >=0.3.11
    - r-goalie >=0.6.14
    - r-pipette >=0.11.1
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.6
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.6.18
    - r-acidcli >=0.2.8
    - r-acidgenerics >=0.6.7
    - r-acidgenomes >=0.5.1
    - r-acidplyr >=0.3.11
    - r-goalie >=0.6.14
    - r-pipette >=0.11.1
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.6

test:
  commands:
    - $R -e "library('PANTHER')"

about:
  home: https://r.acidgenomics.com/packages/panther/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: PANTHER database annotations.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
