{% set version = "0.3.0" %}
{% set github = "https://github.com/acidgenomics/r-chromium" %}

package:
  name: r-chromium
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: e2f58a6141ce55b73d631323360d86d3713bf7870476c2505f457c61f41a3d0b

build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-rhdf5 >=2.42.0
    - bioconductor-s4vectors >=0.36.0
    - bioconductor-singlecellexperiment >=1.20.0
    - bioconductor-summarizedexperiment >=1.28.0
    - r-acidbase >=0.6.12
    - r-acidcli >=0.2.7
    - r-acidexperiment >=0.4.5
    - r-acidgenerics >=0.6.6
    - r-acidgenomes >=0.4.7
    - r-acidplyr >=0.3.6
    - r-acidsinglecell >=0.3.4
    - r-goalie >=0.6.8
    - r-matrix >=1.5.1
    - r-pipette >=0.10.3
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.4
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-rhdf5 >=2.42.0
    - bioconductor-s4vectors >=0.36.0
    - bioconductor-singlecellexperiment >=1.20.0
    - bioconductor-summarizedexperiment >=1.28.0
    - r-acidbase >=0.6.12
    - r-acidcli >=0.2.7
    - r-acidexperiment >=0.4.5
    - r-acidgenerics >=0.6.6
    - r-acidgenomes >=0.4.7
    - r-acidplyr >=0.3.6
    - r-acidsinglecell >=0.3.4
    - r-goalie >=0.6.8
    - r-matrix >=1.5.1
    - r-pipette >=0.10.3
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.4

test:
  commands:
    - $R -e "library('Chromium')"

about:
  home: https://r.acidgenomics.com/packages/chromium/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for 10X Genomics Chromium single cell data.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
