{% set version = "0.8.1.9000" %}
{% set github = "https://github.com/acidgenomics/r-cellosaurus" %}

package:
  name: r-cellosaurus
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 93c1da71a6078bf750c42442bda1b50e19c7c91edd4a4be7f1d7406f46468b00

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports:
    - {{ pin_subpackage('r-cellosaurus', max_pin="x.x") }}

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.6.19
    - r-acidcli >=0.2.8
    - r-acidgenerics >=0.6.8
    - r-acidplyr >=0.4.2
    - r-goalie >=0.6.15
    - r-pipette >=0.12.0
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.6
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.6.19
    - r-acidcli >=0.2.8
    - r-acidgenerics >=0.6.8
    - r-acidplyr >=0.4.2
    - r-goalie >=0.6.15
    - r-pipette >=0.12.0
    - r-stringi >=1.7.12
    - r-syntactic >=0.6.6

test:
  commands:
    - $R -e "library('Cellosaurus')"

about:
  home: https://r.acidgenomics.com/packages/cellosaurus/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Cellosaurus identifier mapping toolkit.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
