{% set version = '0.9.0' %}
{% set github = "https://github.com/hbc/bcbioBase" %}

package:
  name: r-bcbiobase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: f9c3e39f86e07d1af07838f95a0f1cae6f7c142bfb0e13ceb5dd2e16f2941cb2

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-s4vectors >=0.36.0
    - r-acidbase >=0.6.8
    - r-acidcli >=0.2.5
    - r-acidexperiment >=0.4.4
    - r-acidplyr >=0.3.2
    - r-goalie >=0.6.6
    - r-pipette >=0.10.1
    - r-stringr >=1.4.1
    - r-syntactic >=0.6.3
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-s4vectors >=0.36.0
    - r-acidbase >=0.6.8
    - r-acidcli >=0.2.5
    - r-acidexperiment >=0.4.4
    - r-acidplyr >=0.3.2
    - r-goalie >=0.6.6
    - r-pipette >=0.10.1
    - r-stringr >=1.4.1
    - r-syntactic >=0.6.3

test:
  commands:
    - $R -e "library('bcbioBase')"

about:
  home: https://r.acidgenomics.com/packages/bcbiobase/
  dev_url: "{{ github }}"
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions and generics for bcbio R packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - hbc
    - mjsteinbaugh
